---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: joomla
type: Opaque
data:
  dbpassword: {{ include "common.dbpassword.secret" . }}
  rootdbpassword: {{ include "common.rootpassword" . }}
