apiVersion: v2
name: joomla-inetpub
description: Test Helm chart for Joomla

type: application
version: 0.1.5
appVersion: "5.4.0"

dependencies:
- name: common
  version: 1.0.1
  repository: "file://./charts/common"
- name: mysql
  version: 0.1.0
  repository: "file://./charts/mysql"

icon: https://raw.githubusercontent.com/lars-c/helm-chart/main/icons/joomla128-00.png
maintainers:
- email: oss-maint@inetpub.dk
  name: oss-maintainer