apiVersion: v2
name: joomla-inetpub
description: Test Helm chart for Joomla

type: application
version: 0.1.3
appVersion: "5.3.0"

dependencies:
- name: mysql
  version: 0.1.0
  repository: "file://./charts/mysql"

icon: https://raw.githubusercontent.com/lars-c/helm-chart/main/icons/joomla128-00.png
maintainers:
- email: oss-maint@inetpub.dk
  name: oss-maintainer