# Default values for joomla-inetpub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Shared values for all charts
##
global:
  ## JOOMLA_DB_USER / MYSQL_USER
  dbuser: "j210"
  #
  # Database name (JOOMLA_DB_NAME / MYSQL_DATABASE)
  dbname: "joomla_db"
  #
  ## OOMLA_DB_PASSWORD / MYSQL_PASSWORD
  dbpassword: "S3iHysSSAkwRj3SupR33"
  #
  ## JOOMLA_DB_HOST
  joomlaDbHost: "mysqldb"
  #
## Debugging
debug:
  enable: true
  value: "Test"
#
# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: joomla
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "5.4.0-php8.3-apache"

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: LoadBalancer
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80
  ## loadBalancerIP for the Joomla Service
  loadBalancerIP: "192.168.5.76"
##
storage:
  ## Storage class for Joomla PVC
  class: "local-path"
  ## Access mode for Joomla PVC
  accessMode: ReadWriteOnce
  ## Size of Joomla PVC
  size: 2Gi

#### Set container requests and limits for resources
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
##
resources:
  enableLimit: false
  limits:
    memory: "768Mi"
    cpu: "500m"
  enableRequest: true
  requests:
    memory: "256Mi"
    cpu: "250m"
  
## MySQL specific configuration
mysql:
  debug:
    enable: false
    value: "TestMySQL"
  ## This sets the container image for MySQL
  ## ref: https://hub.docker.com/_/mysql
  ##
  image:
    repository: "mysql"
    tag: "8.0"
    pullPolicy: IfNotPresent
  auth:
    rootdbpassword: "bxJK8Q1wd9ZFeDO8bOKbQ9CN"
  ## Tiemzone
  timezone: "Europe/Copenhagen"    
  ##
  storage:
    ## Storage class for MySQL PVC
    class: "local-path"
    ## Access mode for MySQL PVC
    accessMode: ReadWriteOnce
    ## Size of MySQL PVC
    size: 2Gi
  #### Set container requests and limits for resources
  ##
  resources:
    enableLimit: false
    limits:
      memory: "768Mi"
      cpu: "500m"
    enableRequest: true
    requests:
      memory: "512Mi"
      cpu: "250m"
  
