apiVersion: v2
name: joomla-basic
description: Joomla chart with automatic installer
version: 0.4.3
appVersion: "6.0.0"

dependencies:
- name: common
  version: 1.0.0
  repository: "file://./charts/common"
- name: mysql
  version: 1.0.0
  repository: "file://./charts/mysql"

icon: https://raw.githubusercontent.com/lars-c/helm-chart/main/icons/joomla128-00.png
maintainers:
- email: oss-maint@inetpub.dk
  name: oss-maintainer