# Default values for mongo-backup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Name of the StatefulSet
name: "mongodb"
# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 3

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: mongo
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8.0.12"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting the MongoDB authentication credentials.
# More information can be found here: https://docs.mongodb.com/manual/tutorial/enable-authentication
auth:
  rootUsername: "admin"
  rootPassword: "SecurePassword123"

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
# StatefulSet service name
# Must match the service name in the Service definition
serviceName: "mongo-service"

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: None
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

# This is settings for pod resources more information can be found here: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# This is to setup the liveness. MongoDB running but jammed is rare. TCP is enough to detect crash loops.
livenessProbe:
  enabled: true
  tcpSocket:
    port: 27017
  initialDelaySeconds: 15
  timeoutSeconds: 2
  failureThreshold: 5
  periodSeconds: 10
# This is the readiness probe configuration. Using mongosh to check if the database is responsive.
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
  periodSeconds: 5
# This is the startup probe configuration. Using mongosh to check if the database is responsive.
startupProbe:
  enabled: true
  failureThreshold: 40
  periodSeconds: 5

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
## preferred (soft) and required (hard) affinity
##
affinity:
  enabled: false
  preferred: true
  required: false
  #
  preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      key: color
      operator: In
      values:
        - pink
    - weight: 5
      key: color
      operator: In
      values:
        - gray        
    - weight: 5
      key: color
      operator: In
      values:
        - orange
    - weight: 10
      key: color
      operator: In
      values:
        - green        
  requiredDuringSchedulingIgnoredDuringExecution:
    - key: color
      operator: In
      values:
        - green  

## Tolerations for pod assignment
##
tolerationsEnabled: false
tolerations:
  - key: "key1"
    operator: "Equal"
    value: "gray"
    effect: "NoSchedule"
  - key: "key1"
    operator: "Equal"
    value: "orange"
    effect: "NoSchedule"

# MongoDB specific values
mongo:
  port: 27017

# Persistent Volume Claim Template configuration
persistence:
  accessModes:
    - ReadWriteOnce
  # Specify a storage class or set to null to override the default storage class
  storageClass: "local-path"
  size: 1Gi  
