---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joomla-data
  labels:
    app: joomla
spec:
  storageClassName: {{ .Values.storage.class }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}